language: cpp
compiler: gcc
sudo: required
dist: trusty

git:
  depth: false

matrix:
  include:
    - os: linux
      env: BUILD_TYPE=AppImage
    - os: linux
      env: BUILD_TYPE=deb
      services: docker
    - os: linux
      env: BUILD_TYPE=rpm
      services: docker
    - os: windows
      env:
        - BUILD_TYPE=exe
        - QT_BIN="/c/qt/5.6.3/msvc2015/bin"
        - QT_PLUGIN="/c/qt/5.6.3/msvc2015/plugins/platforms"
        - CL_BIN="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86"
        - RC_BIN="/c/Program Files (x86)/Windows Kits/10/bin/10.0.17134.0/x86"
        - UM_LIB="/c/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/um/x86"
        - UCRT_LIB="/c/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/ucrt/x86"
        - MSVCRTD_LIB="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/lib/x86"
        - KCOLORPICKER_LIB="/c/Program Files (x86)/kColorPicker/lib"
        - KIMAGEANNOTATOR_LIB="/c/Program Files (x86)/kImageAnnotator/lib"
        - UM_INCLUDE="/c/Program Files (x86)/Windows Kits/10/Include/10.0.17134.0/um"
        - UCRT_INCLUDE="/c/Program Files (x86)/Windows Kits/10/Include/10.0.17134.0/ucrt"
        - SHARED_INCLUDE="/c/Program Files (x86)/Windows Kits/10/Include/10.0.17134.0/shared"
        - MSVCRTD_INCLUDE="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/include"
        - KCOLORPICKER_INCLUDE="/c/Program Files (x86)/kColorPicker/include"
        - KIMAGEANNOTATOR_INCLUDE="/c/Program Files (x86)/kImageAnnotator/include"

before_install:
  - source ci/scripts/bootstrap.sh

install:
  - source ci/scripts/setup.sh

script:
  - source ci/scripts/build.sh

after_success:
  - source ci/scripts/upload.sh

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
