language: cpp
compiler: gcc
sudo: required
dist: xenial
services: xvfb

git:
  depth: false

jobs:
  include:
    - stage: test
      os: linux
      before_install:
        - sudo add-apt-repository ppa:beineri/opt-qt594-xenial -y
        - sudo apt-get update -qq
      install:
        - git clone git://github.com/DamirPorobic/kColorPicker
        - git clone git://github.com/DamirPorobic/kImageAnnotator
        - sudo apt-get -y install mesa-common-dev libglu1-mesa-dev qt59base qt59x11extras qt59tools qt59svg
        - source /opt/qt*/bin/qt*-env.sh

        - echo "--> Install Extra CMake Modules"
        - git clone git://github.com/KDE/extra-cmake-modules
        - cd extra-cmake-modules
        - mkdir build && cd build
        - cmake ..
        - make && sudo make install
        - cd ../..

        - echo "--> Install kColorPicker"
        - cd kColorPicker
        - mkdir build && cd build
        - cmake .. -DBUILD_EXAMPLE=OFF
        - make && sudo make install
        - cd ../..

        - echo "--> Install kImageAnnotator"
        - cd kImageAnnotator
        - mkdir build && cd build
        - cmake .. -DBUILD_EXAMPLE=OFF
        - make && sudo make install
        - cd ../..
      script:
        - mkdir build ; cd build
        - cmake .. -DBUILD_TESTS=ON ; make
        - xvfb-run --auto-servernum --server-num=1 --server-args="-screen 0 1024x768x24" make test CTEST_OUTPUT_ON_FAILURE=1

    - stage: build
      os: linux
      env: BINARY_TYPE=AppImage
      before_install: source ci/scripts/bootstrap.sh
      install: source ci/scripts/setup.sh
      script: source ci/scripts/build.sh
      after_success: source ci/scripts/upload.sh
    - stage: build
      os: linux
      env: BINARY_TYPE=deb
      services: docker
      before_install: source ci/scripts/bootstrap.sh
      install: source ci/scripts/setup.sh
      script: source ci/scripts/build.sh
      after_success: source ci/scripts/upload.sh
    - stage: build
      os: linux
      env: BINARY_TYPE=rpm
      services: docker
      before_install: source ci/scripts/bootstrap.sh
      install: source ci/scripts/setup.sh
      script: source ci/scripts/build.sh
      after_success: source ci/scripts/upload.sh
    - stage: build
      os: windows
      env: BINARY_TYPE=exe
      before_install: source ci/scripts/bootstrap.sh
      install: source ci/scripts/setup.sh
      script: source ci/scripts/build.sh
      after_success: source ci/scripts/upload.sh
    - stage: build
      os: osx
      env: BINARY_TYPE=app
      before_install: source ci/scripts/bootstrap.sh
      install: source ci/scripts/setup.sh
      script: source ci/scripts/build.sh
      after_success: source ci/scripts/upload.sh

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
