language: cpp
compiler: gcc
sudo: required
dist: trusty

git:
  depth: false

matrix:
  include:
    - os: linux
      env: BUILD_TYPE=AppImage
    - os: linux
      env: BUILD_TYPE=deb
      services: docker
    - os: linux
      env: BUILD_TYPE=rpm
      services: docker
    - os: windows
      env:
        - BUILD_TYPE=exe
        - QT_BIN_PATH="/c/qt/5.6.3/msvc2015/bin"
        - QT_PLUGIN_PATH="/c/qt/5.6.3/msvc2015/plugins/platforms"
        - CL_BIN_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe"
        - KCOLORPICKER_LIB="/c/Program Files (x86)/kColorPicker/lib"
        - KCOLORPICKER_INCLUDE="/c/Program Files (x86)/kColorPicker/include"
        - KIMAGEANNOTATOR_LIB="/c/Program Files (x86)/kImageAnnotator/lib"
        - KIMAGEANNOTATOR_INCLUDE="/c/Program Files (x86)/kImageAnnotator/include"

before_install:
  - source ci/scripts/bootstrap.sh

install:
  - source ci/scripts/setup.sh

script:
  - source ci/scripts/build.sh

after_success:
  - source ci/scripts/upload.sh

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
