language: cpp
compiler: gcc
sudo: required
dist: trusty

git:
  depth: false

matrix:
  include:
    - os: linux
      env: BUILD_TYPE=AppImage
    - os: linux
      env: BUILD_TYPE=deb
    - os: linux
      env: BUILD_TYPE=rpm
      services: docker


before_install:
  - ci/scripts/bootstrap.sh

install:
  - ci/scripts/setup.sh

script:
  - ci/build.sh

#after_success:
#  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
#  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
#  - bash upload.sh ksnip*.AppImage*

deploy:
  provider: releases
  api_key: "GITHUB_TOKEN"
  file_glob: true
  file: ksnip-*
  skip_cleanup: true
  on:
    tags: true

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
