language: cpp
compiler: gcc
sudo: required
dist: xenial
services: xvfb

git:
  depth: false



before_install:
  - source ci/scripts/bootstrap.sh

install:
  - source ci/scripts/setup.sh

script:
  - source ci/scripts/build.sh

after_success:
  - source ci/scripts/upload.sh


jobs:
  include:
    - stage: build
      matrix:
        include:
          - os: linux
            env: BINARY_TYPE=AppImage
          - os: linux
            env: BINARY_TYPE=deb
            services: docker
          - os: linux
            env: BINARY_TYPE=rpm
            services: docker
          - os: windows
            env: BINARY_TYPE=exe
          - os: osx
            env: BINARY_TYPE=app
      before_install:
        - source ci/scripts/bootstrap.sh
      install:
        - source ci/scripts/setup.sh
      script:
        - source ci/scripts/build.sh
      after_success:
        - source ci/scripts/upload.sh
    - stage: test
      os: linux
      env: BINARY_TYPE=AppImage
      before_install:
        - source ci/scripts/bootstrap.sh
      install:
        - source ci/scripts/setup.sh
      script:
        - mkdir build ; cd build
        - cmake .. -DBUILD_TESTS=ON ; make
        - xvfb-run --auto-servernum --server-num=1 --server-args="-screen 0 1024x768x24" make test CTEST_OUTPUT_ON_FAILURE=1

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
