language: cpp
compiler: gcc
sudo: required
dist: trusty

git:
  depth: false

matrix:
  include:
    - os: linux
      env: BUILD_TYPE=AppImage
    - os: linux
      env: BUILD_TYPE=deb
      services: docker
    - os: linux
      env: BUILD_TYPE=rpm
      services: docker
    - os: windows
      env:
        - BUILD_TYPE=exe
        - QT_DIR="/c/qt"
        - QT_VERSION="5.6.3"
        - LIB_DIR="/c/Program Files (x86)"
        - QT_BIN_PATH=$QT_DIR"/"$QT_VERSION"/msvc2015/bin"
        - QT_BIN_PLUGIN=$QT_DIR"/"$QT_VERSION"/msvc2015/plugins/platforms"
        - KCOLORPICKER_LIB=$LIB_DIR"/kColorPicker/lib"
        - KCOLORPICKER_INCLUDE=$LIB_DIR"/kColorPicker/include"
        - KIMAGEANNOTATOR_LIB=$LIB_DIR"/kImageAnnotator/lib"
        - KIMAGEANNOTATOR_INCLUDE=$LIB_DIR"/kImageAnnotator/include"

before_install:
  - source ci/scripts/bootstrap.sh

install:
  - source ci/scripts/setup.sh

script:
  - source ci/scripts/build.sh

after_success:
  - source ci/scripts/upload.sh

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
